Repository aimhubio/aimui, pull requests merged in 2020-07, with the labels that each got.

#7 Allow tag to be hided and add is_hidden column to the db
  client/src/screens/hub/HubExecutableDetailScreen/HubExecutableDetailScreen.less
  client/src/screens/hub/HubTagDetailScreen/HubTagDetailScreen.js
  client/src/screens/hub/HubTagDetailScreen/HubTagDetailScreen.less
  client/src/screens/hub/HubTagDetailScreen/components/TagDangerZone.js
  client/src/ui/components/Line/Line.js
  client/src/ui/components/Line/Line.less
  client/src/ui/components/Segment/Segment.js
  client/src/ui/components/Segment/Segment.less
  server/app/commits/models.py
  server/app/tags/views.py
  server/migrations/versions/e4c2561d5f16_.py
Labels: Status: In progress, enhancement

#17 Support Hiding and Revert Hiding Executables
  client/public/swagger.yaml
  client/src/actions/hub/executables.js
  client/src/components/hub/DangerZone/DangerZone.js
  client/src/screens/hub/HubExecutableDetailScreen/HubExecutableDetailScreen.js
  client/src/screens/hub/HubExecutableDetailScreen/HubExecutableDetailScreen.less
  client/src/screens/hub/HubTagDetailScreen/HubTagDetailScreen.js
  client/src/storeUtils.js
  server/app/commits/models.py
  server/app/executables/models.py
  server/app/executables/views.py
  server/migrations/versions/9f746fd1dd67_.py
Labels: Status: Review needed, enhancement

#25 Update README with sneak peek and getting started
  README.md
Labels: Status: In progress

#27 Update LICENSE to Apache 2
  LICENSE
  LICENSE.md
Labels: approved

#31 Show tags in related experiment detail screen
  client/src/screens/hub/HubExperimentScreen/HubExperimentScreen.js
  client/src/screens/hub/HubExperimentScreen/HubExperimentScreen.less
  client/src/storeUtils.js
Labels: enhancement, review needed

#30 Display Information on Navbar & Add Status Indicator to Sidebar
  client/src/components/hub/CommitNavigation/CommitNavigation.js
  client/src/components/hub/CommitNavigation/CommitNavigation.less
  client/src/components/hub/CurrentRunIndicator/CurrentRunIndicator.js
  client/src/components/hub/CurrentRunIndicator/CurrentRunIndicator.less
  client/src/screens/hub/HubExperimentScreen/HubExperimentScreen.js
  client/src/screens/hub/HubExperimentScreen/HubExperimentScreen.less
  client/src/utils/index.js
  server/app/projects/views.py
Labels: enhancement, review needed

#53 [WIP] Ability to list and edit parameters of attached TF Summary logs
  client/public/swagger.0.0.4.yaml
  client/src/App.js
  client/src/actions/hub/commit.js
  client/src/constants/classes.js
  client/src/constants/screens.js
  client/src/screens/hub/HubExecutableCreateScreen/HubExecutableCreateScreen.js
  client/src/screens/hub/HubExecutableDetailScreen/HubExecutableDetailScreen.js
  client/src/screens/hub/HubExecutableProcessDetailScreen/HubExecutableProcessDetailScreen.js
  client/src/screens/hub/HubExecutablesScreen/HubExecutablesScreen.js
  client/src/screens/hub/HubTFSummaryListScreen/HubTFSummaryListScreen.js
  client/src/screens/hub/HubTFSummaryListScreen/HubTFSummaryListScreen.less
  client/src/screens/hub/HubTagCreateScreen/HubTagCreateScreen.js
  client/src/screens/hub/HubTagDetailScreen/HubTagDetailScreen.js
  client/src/screens/hub/HubTagsScreen/HubTagsScreen.js
  client/src/services/api.js
  client/src/storeUtils.js
  client/src/ui/components/Container/Container.less
  server/app/commits/models.py
  server/app/commits/utils.py
  server/app/commits/views.py
  server/migrations/versions/0475000fba38_.py
Labels: enhancement, in progress, tf summary integration

#52 [fix] Performance improvement for Panel rendering
  client/src/screens/hub/HubMainScreen/components/Panel/Panel.js
Labels: dead body, in progress, panel

#57 Display TF logs parameters in context area
  client/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.js
  client/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.less
  client/src/screens/hub/HubTFSummaryListScreen/HubTFSummaryListScreen.less
  server/adapters/tf_summary_adapter.py
  server/app/commits/utils.py
  server/app/commits/views.py
  server/app/projects/utils.py
Labels: tf summary integration
